
variables:
    CONAN_USERNAME: "user"
    CONAN_REFERENCE: "nanoRange/0.1"
    CONAN_CHANNEL: "channel"
    CONAN_LOGIN_USERNAME: "user"
    
.build-template: &build-template
    before_script:
        - sudo pip install --upgrade conan_package_tools
        - conan user
    script:
        - python build.py

gcc-7:
    image: conanio/gcc7
    variables:
        CONAN_GCC_VERSIONS: "7"
    <<: *build-template

gcc-8:
    image: conanio/gcc8
    variables:
        CONAN_GCC_VERSIONS: "8"
    <<: *build-template

